/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "social-callback": () => import("@/views/_builtin/social-callback/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "app_app-detail": () => import("@/views/app/app-detail/index.vue"),
  "app_app-manager": () => import("@/views/app/app-manager/index.vue"),
  app_chat: () => import("@/views/app/chat/index.vue"),
  "app_rate-limit": () => import("@/views/app/rate-limit/index.vue"),
  blog_article: () => import("@/views/blog/article/index.vue"),
  blog_category: () => import("@/views/blog/category/index.vue"),
  demo_demo: () => import("@/views/demo/demo/index.vue"),
  demo_tree: () => import("@/views/demo/tree/index.vue"),
  "execution_mcp-manager": () => import("@/views/execution/mcp-manager/index.vue"),
  "execution_mcp-manager_registry": () => import("@/views/execution/mcp-manager/registry/index.vue"),
  "execution_mcp-market": () => import("@/views/execution/mcp-market/index.vue"),
  "execution_skill-manager": () => import("@/views/execution/skill-manager/index.vue"),
  "execution_tool-manager": () => import("@/views/execution/tool-manager/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "knowledge_chunk-manager": () => import("@/views/knowledge/chunk-manager/index.vue"),
  "knowledge_document-upload": () => import("@/views/knowledge/document-upload/index.vue"),
  "knowledge_document-upload_step1": () => import("@/views/knowledge/document-upload/step1/index.vue"),
  "knowledge_document-upload_step2": () => import("@/views/knowledge/document-upload/step2/index.vue"),
  "knowledge_knowledge-detail": () => import("@/views/knowledge/knowledge-detail/index.vue"),
  "knowledge_knowledge-manager": () => import("@/views/knowledge/knowledge-manager/index.vue"),
  "model_model-manager": () => import("@/views/model/model-manager/index.vue"),
  monitor_cache: () => import("@/views/monitor/cache/index.vue"),
  monitor_logininfor: () => import("@/views/monitor/logininfor/index.vue"),
  monitor_online: () => import("@/views/monitor/online/index.vue"),
  monitor_operlog: () => import("@/views/monitor/operlog/index.vue"),
  system_client: () => import("@/views/system/client/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_notice: () => import("@/views/system/notice/index.vue"),
  "system_oss-config": () => import("@/views/system/oss-config/index.vue"),
  system_oss: () => import("@/views/system/oss/index.vue"),
  system_post: () => import("@/views/system/post/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "system_tenant-package": () => import("@/views/system/tenant-package/index.vue"),
  system_tenant: () => import("@/views/system/tenant/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  tool_gen: () => import("@/views/tool/gen/index.vue"),
  "workflow_connection-rule-manager": () => import("@/views/workflow/connection-rule-manager/index.vue"),
  "workflow_datasource-manager": () => import("@/views/workflow/datasource-manager/index.vue"),
  workflow_editor: () => import("@/views/workflow/editor/index.vue"),
  "workflow_node-definition": () => import("@/views/workflow/node-definition/index.vue"),
  "workflow_template-editor": () => import("@/views/workflow/template-editor/index.vue"),
  "workflow_workflow-template": () => import("@/views/workflow/workflow-template/index.vue"),
};
