/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      localIcon: 'fluent-book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'ai',
    path: '/ai',
    component: 'layout.base',
    meta: {
      title: 'ai',
      i18nKey: 'route.ai',
      localIcon: 'carbon-bot',
      order: 2
    },
    children: [
      {
        name: 'ai_app',
        path: '/ai/app',
        component: 'layout.base',
        meta: {
          title: 'ai_app',
          i18nKey: 'route.ai_app',
          hideInMenu: true
        },
        children: [
          {
            name: 'ai_app_app-detail',
            path: '/ai/app/app-detail',
            component: 'view.ai_app_app-detail',
            meta: {
              title: 'ai_app_app-detail',
              i18nKey: 'route.ai_app_app-detail',
              hideInMenu: true,
              constant: true
            }
          },
          {
            name: 'ai_app_app-manager',
            path: '/ai/app/app-manager',
            component: 'view.ai_app_app-manager',
            meta: {
              title: 'ai_app_app-manager',
              i18nKey: 'route.ai_app_app-manager'
            }
          },
          {
            name: 'ai_app_chat',
            path: '/ai/app/chat',
            component: 'view.ai_app_chat',
            meta: {
              title: 'ai_app_chat',
              i18nKey: 'route.ai_app_chat',
              constant: true,
              hideInMenu: true
            }
          },
          {
            name: 'ai_app_rate-limit',
            path: '/ai/app/rate-limit',
            component: 'view.ai_app_rate-limit',
            meta: {
              title: 'ai_app_rate-limit',
              i18nKey: 'route.ai_app_rate-limit'
            }
          }
        ]
      },
      {
        name: 'ai_knowledge',
        path: '/ai/knowledge',
        component: 'layout.base',
        meta: {
          title: 'ai_knowledge',
          i18nKey: 'route.ai_knowledge',
          hideInMenu: true
        },
        children: [
          {
            name: 'ai_knowledge_chunk-manager',
            path: '/ai/knowledge/chunk-manager',
            component: 'view.ai_knowledge_chunk-manager',
            meta: {
              title: 'ai_knowledge_chunk-manager',
              i18nKey: 'route.ai_knowledge_chunk-manager'
            }
          },
          {
            name: 'ai_knowledge_document-upload',
            path: '/ai/knowledge/document-upload',
            component: 'view.ai_knowledge_document-upload',
            meta: {
              title: 'ai_knowledge_document-upload',
              i18nKey: 'route.ai_knowledge_document-upload',
              constant: true,
              hideInMenu: true
            },
            children: [
              {
                name: 'ai_knowledge_document-upload_step1',
                path: '/ai/knowledge/document-upload/step1',
                component: 'view.ai_knowledge_document-upload_step1',
                meta: {
                  title: 'ai_knowledge_document-upload_step1',
                  i18nKey: 'route.ai_knowledge_document-upload_step1',
                  constant: true,
                  hideInMenu: true
                }
              },
              {
                name: 'ai_knowledge_document-upload_step2',
                path: '/ai/knowledge/document-upload/step2',
                component: 'view.ai_knowledge_document-upload_step2',
                meta: {
                  title: 'ai_knowledge_document-upload_step2',
                  i18nKey: 'route.ai_knowledge_document-upload_step2',
                  constant: true,
                  hideInMenu: true
                }
              }
            ]
          },
          {
            name: 'ai_knowledge_knowledge-detail',
            path: '/ai/knowledge/knowledge-detail',
            component: 'view.ai_knowledge_knowledge-detail',
            meta: {
              title: 'ai_knowledge_knowledge-detail',
              i18nKey: 'route.ai_knowledge_knowledge-detail'
            }
          },
          {
            name: 'ai_knowledge_knowledge-manager',
            path: '/ai/knowledge/knowledge-manager',
            component: 'view.ai_knowledge_knowledge-manager',
            meta: {
              title: 'ai_knowledge_knowledge-manager',
              i18nKey: 'route.ai_knowledge_knowledge-manager'
            }
          }
        ]
      },
      {
        name: 'ai_model',
        path: '/ai/model',
        component: 'layout.base',
        meta: {
          title: 'ai_model',
          i18nKey: 'route.ai_model',
          hideInMenu: true
        },
        children: [
          {
            name: 'ai_model_mcp-manager',
            path: '/ai/model/mcp-manager',
            component: 'view.ai_model_mcp-manager',
            meta: {
              title: 'ai_model_mcp-manager',
              i18nKey: 'route.ai_model_mcp-manager'
            }
          },
          {
            name: 'ai_model_model-manager',
            path: '/ai/model/model-manager',
            component: 'view.ai_model_model-manager',
            meta: {
              title: 'ai_model_model-manager',
              i18nKey: 'route.ai_model_model-manager'
            }
          },
          {
            name: 'ai_model_skill-manager',
            path: '/ai/model/skill-manager',
            component: 'view.ai_model_skill-manager',
            meta: {
              title: 'ai_model_skill-manager',
              i18nKey: 'route.ai_model_skill-manager'
            }
          },
          {
            name: 'ai_model_tool-manager',
            path: '/ai/model/tool-manager',
            component: 'view.ai_model_tool-manager',
            meta: {
              title: 'ai_model_tool-manager',
              i18nKey: 'route.ai_model_tool-manager'
            }
          }
        ]
      },
      {
        name: 'ai_workflow',
        path: '/ai/workflow',
        component: 'layout.base',
        meta: {
          title: 'ai_workflow',
          i18nKey: 'route.ai_workflow',
          hideInMenu: true,
          constant: true
        },
        children: [
          {
            name: 'ai_workflow_connection-rule-manager',
            path: '/ai/workflow/connection-rule-manager',
            component: 'view.ai_workflow_connection-rule-manager',
            meta: {
              title: 'ai_workflow_connection-rule-manager',
              i18nKey: 'route.ai_workflow_connection-rule-manager'
            }
          },
          {
            name: 'ai_workflow_datasource-manager',
            path: '/ai/workflow/datasource-manager',
            component: 'view.ai_workflow_datasource-manager',
            meta: {
              title: 'ai_workflow_datasource-manager',
              i18nKey: 'route.ai_workflow_datasource-manager'
            }
          },
          {
            name: 'ai_workflow_editor',
            path: '/ai/workflow/editor',
            component: 'view.ai_workflow_editor',
            meta: {
              title: 'ai_workflow_editor',
              i18nKey: 'route.ai_workflow_editor',
              hideInMenu: true,
              constant: true
            }
          },
          {
            name: 'ai_workflow_node-definition',
            path: '/ai/workflow/node-definition',
            component: 'view.ai_workflow_node-definition',
            meta: {
              title: 'ai_workflow_node-definition',
              i18nKey: 'route.ai_workflow_node-definition'
            }
          },
          {
            name: 'ai_workflow_template-editor',
            path: '/ai/workflow/template-editor',
            component: 'view.ai_workflow_template-editor',
            meta: {
              title: 'ai_workflow_template-editor',
              i18nKey: 'route.ai_workflow_template-editor',
              hideInMenu: true,
              constant: true
            }
          },
          {
            name: 'ai_workflow_workflow-template',
            path: '/ai/workflow/workflow-template',
            component: 'view.ai_workflow_workflow-template',
            meta: {
              title: 'ai_workflow_workflow-template',
              i18nKey: 'route.ai_workflow_workflow-template'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_demo',
        path: '/demo/demo',
        component: 'view.demo_demo',
        meta: {
          title: 'demo_demo',
          i18nKey: 'route.demo_demo'
        }
      },
      {
        name: 'demo_tree',
        path: '/demo/tree',
        component: 'view.demo_tree',
        meta: {
          title: 'demo_tree',
          i18nKey: 'route.demo_tree'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      localIcon: 'mdi-monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          localIcon: 'hugeicons-configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      localIcon: 'material-symbols-account-circle-full',
      hideInMenu: true
    }
  }
];
